### ISSUE TITLE
2.0.2 does not compile

### ISSUE THREAD

**Issue by level20peon** [cotestatnt/async-esp-fs-webserver#62]
Compilation already aborts at the library import after upgrading to 2.0.2, any pointers here?

```
In file included from FOO\libraries\AsyncEspFsWebserver\src/AsyncFsWebServer.h:56,
                 from BAR.ino:901:
FOO\libraries\AsyncEspFsWebserver\src/CaptivePortal.hpp:34:10: error: 'bool CaptiveRequestHandler::canHandle(AsyncWebServerRequest*) const' marked 'override', but does not override
   34 |     bool canHandle(AsyncWebServerRequest *request) const override {
      |          ^~~~~~~~~

exit status 1

Compilation error: exit status 1
```

**Comment by level20peon** [comment]
So the _const_ in _const override_ was added with **2.0.0**, so I guess the title is somewhat fuzzy on that regard.

Anyhow, I forgot to include that I am using Arduino IDE 2.3.4 and the esp32 library at version 3.2.0.
